# Change these first
owner: scalereal # Your GitHub organization or username, where this repository lives
repo: notionpack-upptime # The name of this repository

sites:
  - name: NotionPack
    url: https://notionpack-uat.herokuapp.com/admin/
    
assignees:
  - Akash1362000
  - Prathamesh9997

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /notionpack-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NotionPack
  introTitle: "**NotionPack** is a tool to increase your productivity using Notion, developed by ScaleReal."
  navbar:
    - title: App
      href: https://uat-notionpack.netlify.app/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
